version: "3.3"
services:
  fastapi_app:
    image: parser
    build: .
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./fastapi-entrypoint.sh

  redis_fastapi_app:
    image: bitnami/redis:latest
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
