version: "3.3"
services:
  fastapi_app:
    image: parser
    build: .
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./fastapi-entrypoint.sh
    depends_on:
      - mongodb_app

  mongodb_app:
    container_name: ${MONGODB_HOST}
    image: mongo:latest
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./data:/data/db
