version: "3.8"
services:
  fastapi_app:
    build: .
    container_name: ${WEB_HOST}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./entrypoints/fastapi.sh

  celery_beat_app:
    build: .
    container_name: celery_beat
    entrypoint:
      - ./entrypoints/celery_beat.sh
    depends_on:
      - fastapi_app

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}
